Feature/profile page
WildCodeSchool/2023-09-orleans-cda-projet2-groupe-b pull request #10
Opened 2023-12-20 11:22 UTC by herve-perel

## Description

Please include a summary of the change or which issue is fixed.

## Type of change

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Area of change

- [ ] Frontend
- [ ] Backend
- [ ] Other: .....

## General checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I ran `bun run format`/`bun run lint` before commit
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation where needed
- [ ] My changes generate no new warnings
- [ ] I have checked my code and corrected any misspellings
- [ ] I have updated `develop` and merged to my branch before submitting pull request
- [ ] My pull request generate no conflicts with `develop` branch
- [ ] I requested code review from other team members

## Frontend checklist:

- [ ] I followed guidelines for `HTML`/`JSX`/`Typescript`
- [ ] My `Javascript` generate no new console errors
- [ ] I tested my code cross browsers
- [ ] My slice is pixel perfect for both desktop and mobile according to design
- [ ] I conducted basic QA to assure all features are working
- [ ] I tested responsive for mobile and tablet resolutions

## Backend checklist:

- [ ] I tested admin by manually adding content from zero
- [ ] I created easy to use admin experience which is self-explanatory
- [ ] I added description to admin fields in hard-to-understand areas
- [ ] I followed guidelines for naming `Typescript` variables
- [ ] I conducted basic QA to assure all features are working

2023-12-20 12:41 UTC, JorisPineau submitted a review, later dismissed

2023-12-20 15:09 UTC, Abecker37 submitted a review, later dismissed

2023-12-21 08:52 UTC, JorisPineau approved these changes

2023-12-21 10:02 UTC, Abecker37 submitted a review, later dismissed

2023-12-21 11:11 UTC, YDrogen requested changes
Étrange
![image](https://github.com/WildCodeSchool/2023-09-orleans-cda-projet2-groupe-b/assets/13053644/a4ecf222-743a-4f3c-8046-7421d517fbf8)

2023-12-21 11:11 UTC, YDrogen commented on packages/frontend/web/public/images/placeholder.jpg
placeholder de ?

2023-12-21 11:11 UTC, YDrogen commented on packages/frontend/web/src/components/Modal.tsx
> +          <img src='./icons/cross.svg' />
Mauvais chemin

2023-12-21 11:11 UTC, YDrogen commented on packages/frontend/web/src/components/Modal.tsx
> +        }}
Pourquoi ?

2023-12-21 11:11 UTC, YDrogen commented on packages/types/src/profile.ts
> +export type MusiqueButtonStates = {
Pas mal le franglais

2023-12-21 11:11 UTC, YDrogen commented on packages/types/src/profile.ts
Pourquoi mettre les types ici ? Ils seront utilisés dans le backend aussi ?

2023-12-21 11:11 UTC, YDrogen commented on packages/types/src/modal.ts
Pourquoi mettre les types ici ? Ils seront utilisés dans le backend aussi ?

2023-12-21 11:11 UTC, YDrogen commented on packages/frontend/web/src/pages/MyPreferences.tsx
> +        <p className='ms-[5%] text-xl'>{'accept smocking'}</p>
"smock" signifie "blouse"

2023-12-21 11:11 UTC, YDrogen commented on packages/frontend/web/src/pages/MyPreferences.tsx
> +        </button>
Code dupliqué, tu peux faire une boucle

2023-12-21 11:11 UTC, YDrogen commented on packages/frontend/web/src/pages/MyPreferences.tsx
> +      <div className='mt-2 flex justify-around'>
idem

2023-12-21 11:11 UTC, YDrogen commented on packages/frontend/web/src/pages/MyPreferences.tsx
> +  const [musiqueButtonStates, setMusiqueButtonStates] = useState({
Tu peux en profiter pour typer le useState

2023-12-21 11:11 UTC, YDrogen commented on packages/frontend/web/src/router.tsx
> +        path: '/profil',
Lien en français ?

2023-12-21 13:54 UTC, JorisPineau approved these changes

2023-12-22 11:12 UTC, Abecker37 approved these changes

2023-12-22 11:13 UTC, JorisPineau approved these changes

2024-01-04 10:51 UTC, YDrogen commented on packages/frontend/web/src/pages/Profile.tsx
> +          <p className='ms-[5%]'>{'My profil preferences'}</p>
```suggestion
          <p className='ms-[5%]'>{'My profile preferences'}</p>
```

2024-01-04 10:51 UTC, YDrogen commented on packages/frontend/web/src/pages/Profile.tsx
> +        alt='image-profil'
profil : français
profile : anglais

2024-01-04 10:52 UTC, YDrogen commented on packages/frontend/web/src/pages/MyPreferences.tsx
> +          <span className='peer-checked:after:bg-primary me-[5%] ml-4 flex h-5 w-10 flex-shrink-0 items-center rounded-full bg-white  duration-300 ease-in-out after:h-5 after:w-5 after:rounded-full a
double espaces

2024-01-04 10:53 UTC, YDrogen commented on packages/frontend/web/src/pages/MyPreferences.tsx
> +};
Pourquoi mettre ça dans des fonctions ?

2024-01-04 13:42 UTC, JorisPineau approved these changes

2024-01-04 13:42 UTC, jaalazard approved these changes

2024-01-04 14:35 UTC, Abecker37 approved these changes

2024-01-04 15:58 UTC, YDrogen approved these changes

2024-01-04 15:58 UTC, merged