fix(navbar): add link for login
WildCodeSchool/2023-09-orleans-cda-projet2-groupe-b pull request #12
Opened 2023-12-22 14:42 UTC by Abecker37

## Description

Please include a summary of the change or which issue is fixed.

## Type of change

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Area of change

- [ ] Frontend
- [ ] Backend
- [ ] Other: .....

## General checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I ran `bun run format`/`bun run lint` before commit
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation where needed
- [ ] My changes generate no new warnings
- [ ] I have checked my code and corrected any misspellings
- [ ] I have updated `develop` and merged to my branch before submitting pull request
- [ ] My pull request generate no conflicts with `develop` branch
- [ ] I requested code review from other team members

## Frontend checklist:

- [ ] I followed guidelines for `HTML`/`JSX`/`Typescript`
- [ ] My `Javascript` generate no new console errors
- [ ] I tested my code cross browsers
- [ ] My slice is pixel perfect for both desktop and mobile according to design
- [ ] I conducted basic QA to assure all features are working
- [ ] I tested responsive for mobile and tablet resolutions

## Backend checklist:

- [ ] I tested admin by manually adding content from zero
- [ ] I created easy to use admin experience which is self-explanatory
- [ ] I added description to admin fields in hard-to-understand areas
- [ ] I followed guidelines for naming `Typescript` variables
- [ ] I conducted basic QA to assure all features are working

2023-12-22 14:47 UTC, JorisPineau approved these changes

2023-12-22 14:48 UTC, herve-perel submitted a review, later dismissed

2024-01-04 10:56 UTC, YDrogen requested changes

2024-01-04 10:56 UTC, YDrogen commented on packages/frontend/web/src/components/Navbar.tsx
Pourquoi 2 fois `{isLoggedIn ? `
Pourquoi ne pas tout mettre dans le même ?

2024-01-04 13:19 UTC, Abecker37 commented on packages/frontend/web/src/components/Navbar.tsx
Car il y a le premier qui englobe le profil coter mobile et l'autre pour le desktop

2024-01-04 13:21 UTC, Abecker37 commented on packages/frontend/web/src/components/Navbar.tsx
Après si tu à une méthode pour éviter le dédoublement de code pour le mobile et desktop je suis preneur mais je n'avais pas trouver

2024-01-04 14:20 UTC, Abecker37 commented on packages/frontend/web/src/components/Navbar.tsx
tous simplement car sur un profil j'ai une div avec le dropdown pour le desktop et un autre qui mène a la page profil pour le mobile donc je ne vois pas comment je pourrais faire ça dans une seule ternaire sachant que je veux mon dropdown que si je suis en sm md ect

2024-01-04 14:34 UTC, JorisPineau submitted a review, later dismissed

2024-01-04 14:50 UTC, herve-perel approved these changes

2024-01-04 16:02 UTC, YDrogen submitted a review, later dismissed

2024-01-05 09:39 UTC, herve-perel approved these changes

2024-01-05 09:39 UTC, JorisPineau approved these changes

2024-01-05 11:04 UTC, YDrogen approved these changes

2024-01-05 11:04 UTC, merged