add logout
WildCodeSchool/2023-09-orleans-cda-projet2-groupe-b pull request #15
Opened 2024-01-05 15:32 UTC by Abecker37

## Description

Please include a summary of the change or which issue is fixed.

## Type of change

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Area of change

- [ ] Frontend
- [ ] Backend
- [ ] Other: .....

## General checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I ran `bun run format`/`bun run lint` before commit
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation where needed
- [ ] My changes generate no new warnings
- [ ] I have checked my code and corrected any misspellings
- [ ] I have updated `develop` and merged to my branch before submitting pull request
- [ ] My pull request generate no conflicts with `develop` branch
- [ ] I requested code review from other team members

## Frontend checklist:

- [ ] I followed guidelines for `HTML`/`JSX`/`Typescript`
- [ ] My `Javascript` generate no new console errors
- [ ] I tested my code cross browsers
- [ ] My slice is pixel perfect for both desktop and mobile according to design
- [ ] I conducted basic QA to assure all features are working
- [ ] I tested responsive for mobile and tablet resolutions

## Backend checklist:

- [ ] I tested admin by manually adding content from zero
- [ ] I created easy to use admin experience which is self-explanatory
- [ ] I added description to admin fields in hard-to-understand areas
- [ ] I followed guidelines for naming `Typescript` variables
- [ ] I conducted basic QA to assure all features are working

2024-01-07 16:12 UTC, JorisPineau requested changes

2024-01-07 16:12 UTC, JorisPineau commented on packages/frontend/web/src/components/Navbar.tsx
> +                              console.error('Échec de la déconnexion');
"Échec de la déconnexion"

2024-01-07 16:12 UTC, JorisPineau commented on packages/frontend/web/src/components/Navbar.tsx
> +                              'Erreur lors de la déconnexion',
'Erreur lors de la déconnexion'

2024-01-07 16:12 UTC, JorisPineau commented on packages/backend/api/src/auth.ts
> +  res.status(200).send('Déconnecté avec succès');
'Déconnecté avec succès' en anglais

2024-01-08 09:00 UTC, herve-perel approved these changes

2024-01-08 14:33 UTC, JorisPineau approved these changes

2024-01-08 16:07 UTC, YDrogen requested changes

2024-01-08 16:07 UTC, YDrogen commented on packages/backend/api/src/auth.ts
> +  res.status(200).send('Logout Sucessful');
C'est pas du JSON ça

2024-01-16 08:17 UTC, Abecker37 commented on packages/backend/api/src/auth.ts
> +  res.status(200).send('Logout Sucessful');
Tu peux être plus clair ? il faut que j'enlève le res.status ?  c'est mon Token qui est pas bon ?

2024-01-16 13:03 UTC, JorisPineau approved these changes

2024-01-16 13:28 UTC, bugBuster42 approved these changes

2024-01-17 10:05 UTC, YDrogen commented on packages/backend/api/src/auth.ts
> +  res.status(200).send('Logout Sucessful');
Il faut quand même envoyer une réponse, sinon le client va attendre indéfiniment
Mais au format JSON, sinon le client va planter

2024-01-19 10:43 UTC, JorisPineau approved these changes

2024-01-19 10:53 UTC, bugBuster42 approved these changes

2024-01-22 09:25 UTC, YDrogen approved these changes

2024-01-22 09:25 UTC, merged