Feature/publish trip
WildCodeSchool/2023-09-orleans-cda-projet2-groupe-b pull request #16
Opened 2024-01-23 14:26 UTC by JorisPineau

## Description

Please include a summary of the change or which issue is fixed.

## Type of change

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Area of change

- [ ] Frontend
- [ ] Backend
- [ ] Other: .....

## General checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I ran `bun run format`/`bun run lint` before commit
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation where needed
- [ ] My changes generate no new warnings
- [ ] I have checked my code and corrected any misspellings
- [ ] I have updated `develop` and merged to my branch before submitting pull request
- [ ] My pull request generate no conflicts with `develop` branch
- [ ] I requested code review from other team members

## Frontend checklist:

- [ ] I followed guidelines for `HTML`/`JSX`/`Typescript`
- [ ] My `Javascript` generate no new console errors
- [ ] I tested my code cross browsers
- [ ] My slice is pixel perfect for both desktop and mobile according to design
- [ ] I conducted basic QA to assure all features are working
- [ ] I tested responsive for mobile and tablet resolutions

## Backend checklist:

- [ ] I tested admin by manually adding content from zero
- [ ] I created easy to use admin experience which is self-explanatory
- [ ] I added description to admin fields in hard-to-understand areas
- [ ] I followed guidelines for naming `Typescript` variables
- [ ] I conducted basic QA to assure all features are working

2024-01-24 11:13 UTC, Abecker37 requested changes

2024-01-24 11:13 UTC, Abecker37 commented on packages/frontend/web/public/images/background.svg
images en anglais

2024-01-24 11:13 UTC, Abecker37 commented on packages/frontend/web/src/components/publish_trip/Directions.tsx
> +    // console.log('DirectionsService');
ta du code commenté

2024-01-24 11:13 UTC, Abecker37 commented on packages/frontend/web/src/components/publish_trip/Directions.tsx
> +    // console.log('directionsRenderer');
ici aussi

2024-01-25 09:12 UTC, Abecker37 submitted a review, later dismissed

2024-01-25 10:02 UTC, Abecker37 submitted a review, later dismissed

2024-01-25 10:05 UTC, herve-perel submitted a review, later dismissed

2024-01-30 09:57 UTC, YDrogen requested changes
Il me reste le front à review

2024-01-30 09:57 UTC, YDrogen commented on .env.sample
> +REACT_GOOGLE_MAPS_API_KEY=""
Il faut préfixer avec `VITE_` sinon ça sera pas accessible dans le front

2024-01-30 09:57 UTC, YDrogen commented on packages/backend/api/src/router.ts
> +router.use('/', publishTripRouter);
Il vaut mieux mettre une URL ici, genre "trips"

2024-01-30 09:57 UTC, YDrogen commented on packages/backend/api/src/publish-trip.ts
> +publishTripRouter.get('/trips', async (req, res) => {
comme ça ici tu peux juste mettre `/`
et cette route sera accessible sur `/trips`

2024-01-30 09:57 UTC, YDrogen commented on packages/backend/api/src/publish-trip.ts
> +publishTripRouter.post('/publish-trip', async (req, res) => {
et celle ci pourrait être un `/` aussi
elle serait aussi accessible sur `/trips` mais en post

2024-01-30 09:57 UTC, YDrogen commented on packages/backend/migrations/src/migrations/20231218144335-db-edit-reservation-seat.ts
> +}
Les instructions ici sont censées annuler les modifs appliquées dans la fonction `up`
Ça annule pas du tout, ça !! 😬

2024-01-30 09:57 UTC, YDrogen commented on packages/frontend/web/package.json
> +    "@react-google-maps/api": "^2.19.2",
lib pas utilisée ?

2024-02-05 11:14 UTC, Abecker37 requested changes

2024-02-05 11:14 UTC, Abecker37 commented on packages/frontend/web/src/components/publish_trip/Itinerary.tsx
> +        {/* </APIProvider> */}
code commenter

2024-02-05 11:14 UTC, Abecker37 commented on packages/frontend/web/src/components/publish_trip/Itinerary.tsx
> +        {/* <APIProvider apiKey={KEY}> */}
code commenter

2024-02-05 11:16 UTC, herve-perel requested changes

2024-02-05 11:16 UTC, herve-perel commented on packages/frontend/web/src/components/publish_trip/SeatCar.tsx
> +            className={`relative h-[54px] w-[50px] ${classseatInTheCar(seat)}`}
variable mal nommé

2024-02-05 11:28 UTC, Abecker37 submitted a review, later dismissed

2024-02-05 13:32 UTC, herve-perel submitted a review, later dismissed

2024-02-07 11:19 UTC, YDrogen requested changes

2024-02-07 11:19 UTC, YDrogen commented on packages/backend/api/src/router.ts
> +router.use('/publish-trip', publishTripRouter);
Pourquoi "publish" ? trip ça suffit pas ?

2024-02-07 11:19 UTC, YDrogen commented on packages/frontend/web/src/components/publish_trip/Search.tsx
> +
A sortir hors du component

2024-02-07 11:19 UTC, YDrogen commented on packages/frontend/web/src/components/publish_trip/SeatCar.tsx
> +      <h1 className=''>{'deselect empty seats'}</h1>
className vide

2024-02-07 11:19 UTC, YDrogen commented on packages/frontend/web/src/components/publish_trip/SeatCar.tsx
> +      <img src='/icons/line-car.svg' className=' mt-6' />
espace inutile

2024-02-12 08:33 UTC, herve-perel submitted a review, later dismissed

2024-02-12 09:32 UTC, Abecker37 submitted a review, later dismissed

2024-02-13 14:25 UTC, YDrogen requested changes

2024-02-13 14:25 UTC, YDrogen commented on packages/frontend/web/src/components/publish_trip/Search.tsx
> +  watch('to');
sert à rien ?

2024-02-21 13:38 UTC, herve-perel approved these changes

2024-02-23 11:40 UTC, YDrogen requested changes

2024-02-23 11:40 UTC, YDrogen commented on packages/backend/api/src/publish-trip.ts
> +  }
Il manque un try catch ici

2024-02-26 09:04 UTC, YDrogen requested changes

2024-02-26 09:04 UTC, YDrogen commented on packages/backend/api/package.json
> +    "@types/multer": "^1.4.11",
Ça va dans les dev dependencies

2024-02-26 09:24 UTC, herve-perel approved these changes

2024-02-26 10:52 UTC, YDrogen approved these changes

2024-02-26 10:52 UTC, merged