Feature/car
WildCodeSchool/2023-09-orleans-cda-projet2-groupe-b pull request #17
Opened 2024-01-24 14:37 UTC by Abecker37

## Description

add crud for car 

## Type of change

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Area of change

- [ ] Frontend
- [ ] Backend
- [ ] Other: .....

## General checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I ran `bun run format`/`bun run lint` before commit
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation where needed
- [ ] My changes generate no new warnings
- [ ] I have checked my code and corrected any misspellings
- [ ] I have updated `develop` and merged to my branch before submitting pull request
- [ ] My pull request generate no conflicts with `develop` branch
- [ ] I requested code review from other team members

## Frontend checklist:

- [ ] I followed guidelines for `HTML`/`JSX`/`Typescript`
- [ ] My `Javascript` generate no new console errors
- [ ] I tested my code cross browsers
- [ ] My slice is pixel perfect for both desktop and mobile according to design
- [ ] I conducted basic QA to assure all features are working
- [ ] I tested responsive for mobile and tablet resolutions

## Backend checklist:

- [ ] I tested admin by manually adding content from zero
- [ ] I created easy to use admin experience which is self-explanatory
- [ ] I added description to admin fields in hard-to-understand areas
- [ ] I followed guidelines for naming `Typescript` variables
- [ ] I conducted basic QA to assure all features are working

2024-01-25 09:14 UTC, herve-perel requested changes

2024-01-25 09:14 UTC, herve-perel commented on packages/frontend/web/src/pages/AddACar.tsx
> +            />{' '}
je pense pas que ça soit utile  le {' '}

2024-01-25 09:14 UTC, herve-perel commented on packages/frontend/web/src/pages/AddACar.tsx
> +            />{' '}
pareil

2024-01-25 09:14 UTC, herve-perel commented on packages/frontend/web/src/pages/AddACar.tsx
> +            />{' '}
pareil

2024-01-25 09:14 UTC, herve-perel commented on packages/frontend/web/src/pages/AddACar.tsx
> +            />{' '}
pareil

2024-01-25 09:14 UTC, herve-perel commented on packages/frontend/web/src/pages/AddACar.tsx
> +            </label>{' '}
pareil

2024-01-25 09:21 UTC, herve-perel submitted a review, later dismissed

2024-01-25 09:28 UTC, JorisPineau approved these changes

2024-01-30 11:18 UTC, YDrogen requested changes

2024-01-30 11:18 UTC, YDrogen commented on packages/backend/api/src/auth.ts
> +      const userId = await db
C'est un `user` ça, pas un `userId`

2024-01-30 11:18 UTC, YDrogen commented on packages/frontend/web/src/pages/AddACar.tsx
> +import { useNavigate } from 'react-router-dom';
même librairie

2024-01-30 11:18 UTC, YDrogen commented on packages/frontend/web/src/pages/AddACar.tsx
> +  });
L'intérêt d'utiliser `react-hook-form` c'est de ne pas gérer les states soi-même

2024-01-30 11:18 UTC, YDrogen commented on packages/frontend/web/src/pages/AddACar.tsx
> +          </div>
Beaucoup de répétition la dedans, ça se simplifie

2024-01-30 11:18 UTC, YDrogen commented on packages/frontend/web/src/pages/MyCar.tsx
> +  }, []);
Il se passe quoi quand tu `throw` une erreur ?

2024-01-30 11:18 UTC, YDrogen commented on packages/types/src/car.ts
Ça existe pas déjà ce type ?
Doublon

2024-01-30 11:18 UTC, YDrogen commented on packages/frontend/web/src/schemas/validation-car-schema.ts
> +export type ValidationCarSchema = z.infer<typeof validationCarSchema>;
Triplon !

2024-01-30 11:18 UTC, YDrogen commented on packages/backend/api/src/car.ts
> +      res.status(500).send('internalServerError');
J'espère que cette erreur est gérée côté front

2024-01-30 11:18 UTC, YDrogen commented on packages/backend/api/src/car.ts
> +    res.status(500).send('internalServerError');
et toutes les autres aussi

2024-01-30 11:18 UTC, YDrogen commented on packages/backend/api/middleware/user-id.ts
> +    const userid = Number.parseInt(result.payload.sub);
camel case

2024-01-30 11:19 UTC, YDrogen commented on packages/backend/api/middleware/user-id.ts
Très beau copié collé du projet du groupe A

2024-01-30 14:22 UTC, Abecker37 commented on packages/backend/api/middleware/user-id.ts
yep Noémie m'a aider

2024-02-01 11:06 UTC, Abecker37 commented on packages/types/src/car.ts
non il n'existe pas de type regroupant les deux tables car et car_type

2024-02-01 11:07 UTC, Abecker37 commented on packages/frontend/web/src/schemas/validation-car-schema.ts
> +export type ValidationCarSchema = z.infer<typeof validationCarSchema>;
j'avoue ne pas comprendre il y a la même chose dans login validation et register ?

2024-02-02 08:52 UTC, YDrogen commented on packages/types/src/car.ts
Il est en effet différent de celui de `database.ts`
En revanche, il est identique à `ValidationCarSchema`

2024-02-02 10:38 UTC, jaalazard commented on packages/backend/api/middleware/user-id.ts
ahahah mais quel escroc !

2024-02-05 14:20 UTC, Abecker37 commented on packages/types/src/car.ts
ça pose pas problème de l'utiliser ValidationCarSchema puisque c'est de la validation de Zod ?

2024-02-05 14:50 UTC, YDrogen commented on packages/types/src/car.ts
Non, c'est un type

2024-02-05 16:22 UTC, JorisPineau approved these changes

2024-02-05 16:25 UTC, herve-perel submitted a review, later dismissed

2024-02-07 11:25 UTC, YDrogen requested changes

2024-02-07 11:25 UTC, YDrogen commented on packages/backend/api/src/car.ts
> +carRouter.put('/edit/:id', loginIdUser, async (req: Request, res: Response) => {
Pourquoi préciser `/edit` ?

2024-02-07 11:25 UTC, YDrogen commented on packages/backend/api/src/car.ts
> +  '/delete/:id',
Pourquoi préciser `/delete` ?

2024-02-07 11:25 UTC, YDrogen commented on packages/backend/api/src/car.ts
> +          .executeTakeFirst();
Du coup, tant que je suis connecté, je peux supprimer n'importe quelle voiture ?

2024-02-07 11:25 UTC, YDrogen commented on packages/backend/api/src/car.ts
> +        .execute();
Ou modifier d'ailleurs

2024-02-07 11:25 UTC, YDrogen commented on packages/frontend/web/src/router.tsx
> +      { path: '/edit-car/:id', element: <EditCar /> },
Peut mieux faire
`/cars`
`/cars/add`
...

2024-02-07 11:25 UTC, YDrogen commented on packages/frontend/web/src/pages/MyCar.tsx
> +  }, []);
Où est la fonction cleanup ?

2024-02-07 11:25 UTC, YDrogen commented on packages/frontend/web/src/pages/MyCar.tsx
> +import React from 'react';
À quoi ça sert ?

2024-02-07 11:25 UTC, YDrogen commented on packages/frontend/web/src/pages/EditCar.tsx
> +          {' '}
?

2024-02-07 11:25 UTC, YDrogen commented on packages/frontend/web/src/pages/AddACar.tsx
Quasi identique à Edit, y'a moyen de mettre du code en commun

2024-02-08 09:31 UTC, Abecker37 commented on packages/frontend/web/src/pages/EditCar.tsx
> +          {' '}
??

2024-02-08 10:33 UTC, Abecker37 commented on packages/frontend/web/src/pages/MyCar.tsx
> +import React from 'react';
a rien :joy:

2024-02-13 13:14 UTC, JorisPineau approved these changes

2024-02-13 13:14 UTC, herve-perel approved these changes

2024-02-13 15:52 UTC, YDrogen requested changes

2024-02-13 15:52 UTC, YDrogen commented on packages/backend/api/src/car.ts
> +        });
Pas de `res.`quelquechose dans les transactions
Le return dans la transaction permet d'envoyer des données à l'exterieur de celle ci
`const data = await db.transaction() // ...`

2024-02-13 15:52 UTC, YDrogen commented on packages/frontend/web/src/components/FormCar.tsx
> +  const array = [2, 3, 4, 5, 6, 7, 8, 9];
Qu'est-ce ? Que sont ces chiffres ?

2024-02-13 15:52 UTC, YDrogen commented on packages/frontend/web/src/pages/MyCar.tsx
> +import React from 'react';
🤔

2024-02-13 16:01 UTC, Abecker37 commented on packages/frontend/web/src/components/FormCar.tsx
> +  const array = [2, 3, 4, 5, 6, 7, 8, 9];
c'est pour boucler dessus pour le nombre de place dans la voiture j'ai renommer la constante

2024-02-13 16:17 UTC, JorisPineau approved these changes

2024-02-13 16:17 UTC, herve-perel approved these changes

2024-02-14 10:02 UTC, YDrogen requested changes

2024-02-14 10:02 UTC, YDrogen commented on packages/frontend/web/src/components/FormCar.tsx
> +  const numberSeat = [2, 3, 4, 5, 6, 7, 8, 9];
Peut être sorti hors du component

2024-02-14 10:55 UTC, JorisPineau approved these changes

2024-02-14 10:55 UTC, herve-perel approved these changes

2024-02-15 10:47 UTC, YDrogen approved these changes

2024-02-15 10:47 UTC, merged