Feature/search trip
WildCodeSchool/2023-09-orleans-cda-projet2-groupe-b pull request #18
Opened 2024-01-31 09:49 UTC by JorisPineau

## Description

Please include a summary of the change or which issue is fixed.

## Type of change

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Area of change

- [ ] Frontend
- [ ] Backend
- [ ] Other: .....

## General checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I ran `bun run format`/`bun run lint` before commit
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation where needed
- [ ] My changes generate no new warnings
- [ ] I have checked my code and corrected any misspellings
- [ ] I have updated `develop` and merged to my branch before submitting pull request
- [ ] My pull request generate no conflicts with `develop` branch
- [ ] I requested code review from other team members

## Frontend checklist:

- [ ] I followed guidelines for `HTML`/`JSX`/`Typescript`
- [ ] My `Javascript` generate no new console errors
- [ ] I tested my code cross browsers
- [ ] My slice is pixel perfect for both desktop and mobile according to design
- [ ] I conducted basic QA to assure all features are working
- [ ] I tested responsive for mobile and tablet resolutions

## Backend checklist:

- [ ] I tested admin by manually adding content from zero
- [ ] I created easy to use admin experience which is self-explanatory
- [ ] I added description to admin fields in hard-to-understand areas
- [ ] I followed guidelines for naming `Typescript` variables
- [ ] I conducted basic QA to assure all features are working

2024-02-12 08:35 UTC, herve-perel approved these changes

2024-02-12 09:29 UTC, Abecker37 approved these changes

2024-02-13 16:04 UTC, YDrogen requested changes

2024-02-13 16:04 UTC, YDrogen commented on packages/frontend/web/src/pages/SearchTrip.tsx
> +  const passengers = [1, 2, 3, 4, 5, 6, 7, 8];
why, pourquoi est-ce ici ? Que sont ces séquences de chiffres à la fin ??

2024-02-13 16:04 UTC, YDrogen commented on packages/frontend/web/src/pages/SearchTrip.tsx
> +      <div className=' text-primary flex h-[750px] w-[600px] justify-center bg-black'>
espace vide

2024-02-13 16:04 UTC, YDrogen commented on packages/frontend/web/src/pages/SearchTrip.tsx
> +} from '@app/types/src/search-trip-validation';
mauvais import

2024-02-13 16:04 UTC, YDrogen commented on packages/frontend/web/src/components/CardTrip.tsx
> +        const travelTimeFormat = `${new Date(travelTime).getHours().toString().padStart(2, '0')}h${new Date(travelTime).getMinutes().toString().padStart(2, '0')}`;
Ça peut sortir du return ça il me semble
Y'a du code en double aussi j'ai l'impression 🌮

2024-02-21 13:35 UTC, Abecker37 submitted a review, later dismissed

2024-02-21 13:39 UTC, herve-perel submitted a review, later dismissed

2024-02-23 13:10 UTC, YDrogen requested changes

2024-02-23 13:10 UTC, YDrogen commented on packages/frontend/web/package.json
> +    "@hookform/resolvers": "^3.3.4"
C'est pas un type ça :(

2024-02-26 10:48 UTC, herve-perel submitted a review, later dismissed

2024-02-26 13:30 UTC, herve-perel approved these changes

2024-02-26 13:36 UTC, YDrogen requested changes

2024-02-26 13:36 UTC, YDrogen commented on packages/types/src/index.ts
> +export * from '@app/shared/src/search-trip-validation';
mauvais chemin

2024-02-26 13:48 UTC, herve-perel approved these changes

2024-02-26 14:43 UTC, YDrogen approved these changes

2024-02-26 14:43 UTC, merged