Feature/init db
WildCodeSchool/2023-09-orleans-cda-projet2-groupe-b pull request #4
Opened 2023-11-24 15:41 UTC by JorisPineau

## Description

Please include a summary of the change or which issue is fixed.

## Type of change

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Area of change

- [ ] Frontend
- [ ] Backend
- [ ] Other: .....

## General checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I ran `bun run format`/`bun run lint` before commit
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation where needed
- [ ] My changes generate no new warnings
- [ ] I have checked my code and corrected any misspellings
- [ ] I have updated `develop` and merged to my branch before submitting pull request
- [ ] My pull request generate no conflicts with `develop` branch
- [ ] I requested code review from other team members

## Frontend checklist:

- [ ] I followed guidelines for `HTML`/`JSX`/`Typescript`
- [ ] My `Javascript` generate no new console errors
- [ ] I tested my code cross browsers
- [ ] My slice is pixel perfect for both desktop and mobile according to design
- [ ] I conducted basic QA to assure all features are working
- [ ] I tested responsive for mobile and tablet resolutions

## Backend checklist:

- [ ] I tested admin by manually adding content from zero
- [ ] I created easy to use admin experience which is self-explanatory
- [ ] I added description to admin fields in hard-to-understand areas
- [ ] I followed guidelines for naming `Typescript` variables
- [ ] I conducted basic QA to assure all features are working

2023-11-24 15:43 UTC, Abecker37 submitted a review, later dismissed

2023-11-24 15:54 UTC, herve-perel approved these changes

2023-11-25 08:49 UTC, YDrogen requested changes

2023-11-25 08:49 UTC, YDrogen commented on packages/backend/migrations/src/migrations/20231124095547-init-bdd.ts
> +  await db.schema.dropTable('messaging').ifExists().execute();
Il faut inverser
Les tables créées en dernier doivent être supprimées en premier

2023-11-25 08:49 UTC, YDrogen commented on packages/backend/migrations/src/migrations/20231124095547-init-bdd.ts
> +    .addColumn('travel_time', 'datetime', (col) => col.notNull())
La durée du trajet ne peut pas être une date

2023-11-25 08:49 UTC, YDrogen commented on packages/backend/migrations/src/migrations/20231124095547-init-bdd.ts
> +    .addColumn('is_auto_validation', 'boolean', (col) => col.notNull())
```suggestion
    .addColumn('should_auto_validate', 'boolean', (col) => col.notNull())
```
"est auto validation" -> "devrait auto valider"

2023-11-25 08:49 UTC, YDrogen commented on packages/backend/migrations/src/migrations/20231124095547-init-bdd.ts
> +    .addColumn('is_with_toll', 'boolean', (col) => col.notNull())
```suggestion
    .addColumn('has_tolls', 'boolean', (col) => col.notNull())
```
"est avec péage" -> "a (des) péages"

2023-11-25 08:49 UTC, YDrogen commented on packages/types/src/database.ts
> +  is_with_toll: boolean;
bien penser à mettre à jour ça

2023-11-27 13:07 UTC, herve-perel submitted a review, later dismissed

2023-11-27 16:28 UTC, herve-perel submitted a review, later dismissed

2023-11-28 09:17 UTC, YDrogen requested changes
Les migrations ne fonctionnent pas

2023-11-28 11:12 UTC, herve-perel approved these changes

2023-11-28 13:01 UTC, herve-perel approved these changes

2023-11-28 15:10 UTC, YDrogen approved these changes

2023-11-28 15:23 UTC, herve-perel approved these changes

2023-11-28 15:45 UTC, herve-perel approved these changes

2023-11-28 15:49 UTC, YDrogen approved these changes

2023-11-28 16:17 UTC, Abecker37 approved these changes

2023-11-29 08:25 UTC, merged