navbar
WildCodeSchool/2023-09-orleans-cda-projet2-groupe-b pull request #5
Opened 2023-12-04 15:51 UTC by Abecker37

## Description

Please include a summary of the change or which issue is fixed.

## Type of change

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Area of change

- [ ] Frontend
- [ ] Backend
- [ ] Other: .....

## General checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I ran `bun run format`/`bun run lint` before commit
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation where needed
- [ ] My changes generate no new warnings
- [ ] I have checked my code and corrected any misspellings
- [ ] I have updated `develop` and merged to my branch before submitting pull request
- [ ] My pull request generate no conflicts with `develop` branch
- [ ] I requested code review from other team members

## Frontend checklist:

- [ ] I followed guidelines for `HTML`/`JSX`/`Typescript`
- [ ] My `Javascript` generate no new console errors
- [ ] I tested my code cross browsers
- [ ] My slice is pixel perfect for both desktop and mobile according to design
- [ ] I conducted basic QA to assure all features are working
- [ ] I tested responsive for mobile and tablet resolutions

## Backend checklist:

- [ ] I tested admin by manually adding content from zero
- [ ] I created easy to use admin experience which is self-explanatory
- [ ] I added description to admin fields in hard-to-understand areas
- [ ] I followed guidelines for naming `Typescript` variables
- [ ] I conducted basic QA to assure all features are working

2023-12-04 16:12 UTC, bugBuster42 approved these changes

2023-12-04 16:12 UTC, bugBuster42 commented on packages/frontend/web/src/components/Navbar.tsx
peux -être mettre les titre du dropdown au singulier, comme tu as fait avec "My information"

2023-12-05 08:11 UTC, herve-perel submitted a review, later dismissed

2023-12-05 08:13 UTC, JorisPineau approved these changes

2023-12-05 08:13 UTC, JorisPineau commented on packages/frontend/web/src/components/Navbar.tsx
> +            <div className='aria-hidden absolute right-2 top-14 mt-2 w-60 rounded-md border bg-[#008689]'>
#008689 variable color

2023-12-05 13:06 UTC, JorisPineau submitted a review, later dismissed

2023-12-05 14:21 UTC, bugBuster42 approved these changes

2023-12-05 16:03 UTC, YDrogen requested changes

2023-12-05 16:03 UTC, YDrogen commented on packages/frontend/web/src/components/Navbar.tsx
> +import trip from '../assets/icons/trip.svg';
Une raison de pas les mettre dans le dossier `public` ?

2023-12-05 16:03 UTC, YDrogen commented on packages/frontend/web/src/components/Navbar.tsx
C'est pas mieux au pluriel justement ?

2023-12-05 16:16 UTC, JorisPineau approved these changes

2023-12-05 16:17 UTC, herve-perel approved these changes

2023-12-05 16:17 UTC, bugBuster42 approved these changes

2023-12-06 08:05 UTC, herve-perel submitted a review, later dismissed

2023-12-06 08:13 UTC, JorisPineau approved these changes

2023-12-06 08:14 UTC, bugBuster42 approved these changes

2023-12-06 09:21 UTC, YDrogen commented
Il suffit pas de resolve les conversations pour les valider

2023-12-06 10:27 UTC, herve-perel approved these changes

2023-12-06 10:33 UTC, herve-perel submitted a review, later dismissed

2023-12-06 10:36 UTC, JorisPineau submitted a review, later dismissed

2023-12-06 10:36 UTC, JorisPineau commented on packages/frontend/web/src/globals.css
> +    --secondary: #0c8587;
primary

2023-12-06 10:36 UTC, JorisPineau commented on packages/frontend/web/src/globals.css
> +    --grey: #494d55;
secondary

2023-12-06 10:38 UTC, herve-perel approved these changes

2023-12-06 11:03 UTC, YDrogen requested changes
Pourquoi tout le theme se trouve dans cette PR ?

2023-12-06 11:12 UTC, JorisPineau approved these changes

2023-12-06 12:26 UTC, YDrogen requested changes

2023-12-06 12:26 UTC, YDrogen commented on packages/frontend/web/tailwind.config.js
![image](https://github.com/WildCodeSchool/2023-09-orleans-cda-projet2-groupe-b/assets/13053644/e856c81b-1ebd-4065-9f4a-8673011ab724)
Y'a pas un potentiel problème avec `plugins` ?

2023-12-06 12:26 UTC, YDrogen commented on packages/frontend/web/src/globals.css
> +    font-family: 'Inter', sans-serif;
https://tailwindcss.com/docs/font-family

2023-12-06 13:11 UTC, bugBuster42 approved these changes

2023-12-06 13:38 UTC, herve-perel approved these changes

2023-12-06 14:17 UTC, YDrogen approved these changes

2023-12-06 14:17 UTC, merged