Feature/login
WildCodeSchool/2023-09-orleans-cda-projet2-groupe-b pull request #6
Opened 2023-12-04 16:18 UTC by herve-perel

## Description

Please include a summary of the change or which issue is fixed.

## Type of change

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Area of change

- [ ] Frontend
- [ ] Backend
- [ ] Other: .....

## General checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I ran `bun run format`/`bun run lint` before commit
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation where needed
- [ ] My changes generate no new warnings
- [ ] I have checked my code and corrected any misspellings
- [ ] I have updated `develop` and merged to my branch before submitting pull request
- [ ] My pull request generate no conflicts with `develop` branch
- [ ] I requested code review from other team members

## Frontend checklist:

- [ ] I followed guidelines for `HTML`/`JSX`/`Typescript`
- [ ] My `Javascript` generate no new console errors
- [ ] I tested my code cross browsers
- [ ] My slice is pixel perfect for both desktop and mobile according to design
- [ ] I conducted basic QA to assure all features are working
- [ ] I tested responsive for mobile and tablet resolutions

## Backend checklist:

- [ ] I tested admin by manually adding content from zero
- [ ] I created easy to use admin experience which is self-explanatory
- [ ] I added description to admin fields in hard-to-understand areas
- [ ] I followed guidelines for naming `Typescript` variables
- [ ] I conducted basic QA to assure all features are working

2023-12-05 08:13 UTC, Abecker37 approved these changes
j'approuve la connexion et le register

2023-12-05 14:44 UTC, bugBuster42 approved these changes

2023-12-05 15:25 UTC, Abecker37 submitted a review, later dismissed

2023-12-06 09:01 UTC, Abecker37 submitted a review, later dismissed

2023-12-06 09:43 UTC, bugBuster42 approved these changes

2023-12-06 09:59 UTC, JorisPineau submitted a review, later dismissed

2023-12-06 11:17 UTC, YDrogen requested changes

2023-12-06 11:17 UTC, YDrogen commented on packages/types/src/auth.ts
> +  created_at: Date;
Pourquoi le `created_at` aurait besoin d'être dans le body ?

2023-12-06 11:17 UTC, YDrogen commented on packages/types/src/auth.ts
Il s'agit du Login ou du Register ? Si ce n'est pas les deux, il faut 2 types différents
ex: Pas besoin de rentrer la date de naissance pour la connexion

2023-12-06 11:17 UTC, YDrogen commented on packages/types/src/auth.ts
> +  economy_achieved: number;
C'est l'utilisateur qui dit combien de km il veut au moment de s'inscrire ?

2023-12-06 14:51 UTC, Abecker37 approved these changes

2023-12-06 15:47 UTC, merged